import pandas as pd
import anndata as ad
import numpy as np
import os
import argparse
from sklearn.cluster import AgglomerativeClustering as ac
import scanpy as sc
sc.set_figure_params(figsize=(5,5))

def plot_wells(adata):
    wells = adata.obs["well"].unique().to_list()
    for well in wells:
        adata_well = adata[adata.obs["well"]==well, :]
        # clust_max = int(adata.obs['cluster'].max())
        sc.pl.scatter(adata_well, x='X', y='Y', color='cluster', size=250, show=False, title=well + " unified, coordinates", save=well + "_unified_coord.png", frameon=True)

        sc.pl.scatter(adata_well, x='umap1', y='umap2', color='cluster', size=100, show=False, title=well + " unified, UMAP scatter", save=well + "_unified_UMAP_scatter.png", frameon=True)

def plot_scatter(adata_x):
	adata_x.obs['cluster'] = adata_x.obs['cluster'].astype('category')
	sc.pl.scatter(adata_x, x='umap1', y='umap2', color='cluster', size=30, title="UMAP with unified clusters", save="UMAP_unified_cluster_map.png", show=False)

	sc.pl.scatter(adata_x, x='umap1', y='umap2', color='well', size=30, title="UMAP with coded wells", save="UMAP_unified_well_map.png", alpha=0.7, show=False)

def match_cluster_number_to_desc(adata_scan, adata_desc):
	cluster_number = len(adata_desc.obs['cluster'].unique())
	hc = ac(n_clusters=cluster_number, affinity='euclidean', linkage='ward')
	adata_scan.obs['cluster'] = hc.fit_predict(adata_scan.uns['UMAP_cluster_embedding'])
	adata_scan.obs['cluster'] = adata_scan.obs['cluster'].astype('category')

	return adata_scan

def pick_cluster_non_singlet_cluster_list(gene, adata):
	clusters = adata.obs['cluster'].unique()
	top_clust = 'all'
	top_sum = 0
	non_single_list = []
	for clust in clusters:
		arr = adata[adata.obs['cluster']==clust, adata.var['gene_symbol']==gene]
		if arr.X.shape[0] > 1:
			non_single_list.append(clust)
		clust_sum = np.sum(arr.X)/arr.X.shape[0]
		if clust_sum > top_sum:
			top_clust = [0]
			top_sum = clust_sum
			top_clust[0] = str(clust)
	if not top_clust == 'all':
		arr = adata[adata.obs['cluster']==int(top_clust[0]), adata.var['gene_symbol']==gene]
	return top_clust, top_sum, non_single_list


if __name__ == "__main__":
	parser = argparse.ArgumentParser()
	parser.add_argument("-d", "--desc", type=str, help="path to the DESC AnnData file")
	parser.add_argument("-s", "--scanorama", type=str, help="path to the scanorama-clustered AnnData file")
	parser.add_argument("-o", "--output", type=str, default="../results/")
	parser.add_argument("-t", "--timestamp", type=str)
	parser.add_argument("-g", "--gene", type=str)
	parser.add_argument("-m", "--match", type=int, default=0, help="Match the number of clusters to the one generated by DESC algorithm if int != 0")
	args = parser.parse_args()
	print(args.match)
	output_folder = args.output + "result_" + args.timestamp + "/cluster_analysis/"

	if not os.path.isdir(output_folder):
		os.makedirs(output_folder)

	adata_scan = ad.read_h5ad(args.scanorama)
	adata_desc = ad.read_h5ad(args.desc)
	print(adata_scan)

	adata_desc.obs['X'] = adata_desc.obs['feature'].str.extract('X([0-9.]+)', expand=True).astype('float32')
	adata_desc.obs['Y'] = adata_desc.obs['feature'].str.extract('_([0-9.]+)', expand=True).astype('float32')
	adata_desc.obs['umap1'] = adata_desc.obsm['X_umap0.9'][:, 0]
	adata_desc.obs['umap2'] = adata_desc.obsm['X_umap0.9'][:, 1]
	adata_desc.obs['cluster'] = adata_desc.obs['desc_0.9']
	try:
		del adata_scan.uns['cluster_colors']
		del adata_scan.uns['well_colors']
	except:
		pass
	if args.match != 0:
		print("matching")
		adata_scan = match_cluster_number_to_desc(adata_desc=adata_desc, adata_scan=adata_scan)
	print(len(adata_desc.obs['cluster'].unique()), " clusters in DESC dataset")
	print(len(adata_scan.obs['cluster'].unique()), " clusters in scanorama dataset")
	os.chdir(output_folder)
	pd.DataFrame(adata_scan.X).to_csv("scan_X.csv")
	pd.DataFrame(adata_desc.X).to_csv("desc_X.csv")

	# adata_scan.write("scanorama_anndata_final_cluster.h5ad")
	# adata_desc.write("DESC_anndata_final_cluster.h5ad")

		
	for i, j in zip(["DESC_plot", "scanorama_plot"], [adata_desc, adata_scan]):
		if not os.path.isdir(i):
			os.mkdir(i)
		os.chdir(i)
		plot_scatter(j)
		plot_wells(j)
		top_clust, top_sum, non_single_list = pick_cluster_non_singlet_cluster_list(gene=args.gene, adata=j)
		print("The top cluster for ", args.gene, " is cluster ", top_clust[0], "with the average of ", top_sum, " transcripts per feature!")
		j.obs['cluster'] =j.obs['cluster'].astype('str').astype('category')

		sc.tl.rank_genes_groups(j, n_genes=50, groupby='cluster', method='wilcoxon', key_added = "wilcoxon_all", groups=non_single_list)
		sc.pl.rank_genes_groups(j, key="wilcoxon_all", save=i + "_DE_genes_by_rank_all.png", show=False)
		sc.tl.rank_genes_groups(j, n_genes=50, groupby='cluster', method='wilcoxon', key_added = "wilcoxon", groups=top_clust)
		sc.pl.rank_genes_groups(j, key="wilcoxon", save=i + "_DE_genes_by_rank_top.png", show=False)
		col = 100
		if top_clust == 'all':
			top_clust=None
			col = 10
		j.X = np.power(10, j.X)
		sc.pl.rank_genes_groups_heatmap(j, n_genes=col, key="wilcoxon", show_gene_labels=True, groupby='cluster', groups=top_clust, save=i + "_heatmap.png", show=False)
		sc.pl.rank_genes_groups_matrixplot(j, n_genes=col, key="wilcoxon", groupby="cluster", groups=top_clust, show=False, save=i + "_expression_matrix_plot")
		os.chdir("../")


